# This is a basic workflow to help you get started with Actions

name: TestCafe work flow

on:[push]

jobs:
  name: Run Testcafe tests
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: install testcafe and run
      - uses: DevExpress/testcafe-action@latest
        with:
         args: "chrome test"
